### ISSUE TITLE
Finding files by tags

### ISSUE THREAD

**Issue by ArsenijSerjogin** [ArsenijSerjogin/TagExplorer#17]
If user select one or more tag, need start to try find files with that tags.
### Do:
- [ ] Check is array of [selected tags](https://github.com/ArsenijSerjogin/TagExplorer/issues/16) empty
- [ ] if not try to find files
   - [ ] Check updates in [selecting](https://github.com/ArsenijSerjogin/TagExplorer/issues/16), and if they are => start search again
   - [ ] Write method for [tags DB](https://github.com/ArsenijSerjogin/TagExplorer/issues/12) for check file for tags presence, and return they if true
   - [ ] Write method for check all files who start from current exist path, and save result
   - [ ] Find way to display all passed files
