### ISSUE TITLE
3. Tags [initial]

### ISSUE THREAD

**Issue by ArsenijSerjogin** [ArsenijSerjogin/TagExplorer#20]
Tags create semantic file system. 

- [ ] Add class [Tag](https://github.com/ArsenijSerjogin/TagExplorer/issues/11)
- [ ] Implement [data base](https://github.com/ArsenijSerjogin/TagExplorer/issues/12)
- [ ] [Display files](https://github.com/ArsenijSerjogin/TagExplorer/issues/13) with their tags
- [ ] Create [tag list panel](https://github.com/ArsenijSerjogin/TagExplorer/issues/14)
- [ ] Implement adding [new tag](https://github.com/ArsenijSerjogin/TagExplorer/issues/15)
- [ ] Add [ways to select](https://github.com/ArsenijSerjogin/TagExplorer/issues/16) tags
- [ ] [Find files](https://github.com/ArsenijSerjogin/TagExplorer/issues/17) with appended tags
- [ ] Do possible [edit file tags](https://github.com/ArsenijSerjogin/TagExplorer/issues/18)  
- [ ] Add ways for [edit tag](https://github.com/ArsenijSerjogin/TagExplorer/issues/19)
